### ISSUE TITLE
Add LICENSE file

### ISSUE THREAD

**Issue by madjokal** [JuliaBinaryWrappers/JpegTurbo_jll.jl#1]

**Comment by giordano** [comment]
We usually install licenses in `shares/licenses/PACKAGE_NAME/`, this package was probably built before we started automatically installing the license, but do note that it's also in `share/doc/libjpeg-turbo`

**Comment by madjokal** [comment]
I see that most jll packages include a LICENSE file. And not on all cases the jll package license matches the artifact license.

**Comment by giordano** [comment]
> I see that most jll packages include a LICENSE file.

Right, this is missing the license in wrapper, I thought you were referring to the license inside the tarball. OK, I'll add it.

> And not on all cases the jll package license matches the artifact license.  

Yes, the license of the jll package is independent from that of the tarball, see https://juliapackaging.github.io/BinaryBuilder.jl/dev/jll/#Anatomy-of-a-JLL-package
